-- 01_setup.sql  Create database, schemas, and warehouse
CREATE DATABASE IF NOT EXISTS ONETRUTH;
CREATE SCHEMA IF NOT EXISTS ONETRUTH.RAW;
CREATE SCHEMA IF NOT EXISTS ONETRUTH.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS ONETRUTH.APP;

CREATE WAREHOUSE IF NOT EXISTS ONETRUTH_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE ONETRUTH;
USE WAREHOUSE ONETRUTH_WH;
