-- 19_masking_policy.sql  Hide cost columns from LOGISTICS_ROLE
CREATE OR REPLACE MASKING POLICY ONETRUTH.RAW.MASK_COST_FROM_LOGISTICS
  AS (val NUMBER(38,2)) RETURNS NUMBER(38,2) ->
  CASE WHEN CURRENT_ROLE() = 'LOGISTICS_ROLE' THEN NULL ELSE val END;

ALTER TABLE ONETRUTH.RAW.ORDERS_ERP ALTER COLUMN unit_price
  SET MASKING POLICY ONETRUTH.RAW.MASK_COST_FROM_LOGISTICS;
ALTER TABLE ONETRUTH.RAW.SHIPMENTS_LOGISTICS ALTER COLUMN freight_cost
  SET MASKING POLICY ONETRUTH.RAW.MASK_COST_FROM_LOGISTICS;
ALTER TABLE ONETRUTH.RAW.SHIPMENTS_LOGISTICS ALTER COLUMN duty_cost
  SET MASKING POLICY ONETRUTH.RAW.MASK_COST_FROM_LOGISTICS;
ALTER TABLE ONETRUTH.RAW.SHIPMENTS_LOGISTICS ALTER COLUMN handling_cost
  SET MASKING POLICY ONETRUTH.RAW.MASK_COST_FROM_LOGISTICS;
