-- 20_grants.sql  Privileges for all three persona roles

-- Warehouse
GRANT USAGE ON WAREHOUSE ONETRUTH_WH TO ROLE PLANNING_ROLE;
GRANT USAGE ON WAREHOUSE ONETRUTH_WH TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON WAREHOUSE ONETRUTH_WH TO ROLE LOGISTICS_ROLE;

-- Database
GRANT USAGE ON DATABASE ONETRUTH TO ROLE PLANNING_ROLE;
GRANT USAGE ON DATABASE ONETRUTH TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON DATABASE ONETRUTH TO ROLE LOGISTICS_ROLE;

-- Schemas
GRANT USAGE ON SCHEMA ONETRUTH.RAW TO ROLE PLANNING_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.RAW TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.RAW TO ROLE LOGISTICS_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.SEMANTIC TO ROLE PLANNING_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.SEMANTIC TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.SEMANTIC TO ROLE LOGISTICS_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.APP TO ROLE PLANNING_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.APP TO ROLE PROCUREMENT_ROLE;
GRANT USAGE ON SCHEMA ONETRUTH.APP TO ROLE LOGISTICS_ROLE;

-- SELECT on RAW tables and views
GRANT SELECT ON ALL TABLES IN SCHEMA ONETRUTH.RAW TO ROLE PLANNING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ONETRUTH.RAW TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA ONETRUTH.RAW TO ROLE LOGISTICS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONETRUTH.RAW TO ROLE PLANNING_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONETRUTH.RAW TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONETRUTH.RAW TO ROLE LOGISTICS_ROLE;

-- SELECT on APP views
GRANT SELECT ON ALL VIEWS IN SCHEMA ONETRUTH.APP TO ROLE PLANNING_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONETRUTH.APP TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ONETRUTH.APP TO ROLE LOGISTICS_ROLE;

-- Semantic view
GRANT SELECT ON SEMANTIC VIEW ONETRUTH.SEMANTIC.SUPPLY_CHAIN_SV TO ROLE PLANNING_ROLE;
GRANT SELECT ON SEMANTIC VIEW ONETRUTH.SEMANTIC.SUPPLY_CHAIN_SV TO ROLE PROCUREMENT_ROLE;
GRANT SELECT ON SEMANTIC VIEW ONETRUTH.SEMANTIC.SUPPLY_CHAIN_SV TO ROLE LOGISTICS_ROLE;

-- Cortex Analyst access
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PLANNING_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PROCUREMENT_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE LOGISTICS_ROLE;

-- Grant roles to user
GRANT ROLE PLANNING_ROLE TO USER SUNNYPATHAK979;
GRANT ROLE PROCUREMENT_ROLE TO USER SUNNYPATHAK979;
GRANT ROLE LOGISTICS_ROLE TO USER SUNNYPATHAK979;
